// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// basic types definition
type ChainID struct {
	ChainId              uint64   `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainID) Reset()         { *m = ChainID{} }
func (m *ChainID) String() string { return proto.CompactTextString(m) }
func (*ChainID) ProtoMessage()    {}
func (*ChainID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ChainID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainID.Unmarshal(m, b)
}
func (m *ChainID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainID.Marshal(b, m, deterministic)
}
func (m *ChainID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainID.Merge(m, src)
}
func (m *ChainID) XXX_Size() int {
	return xxx_messageInfo_ChainID.Size(m)
}
func (m *ChainID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainID.DiscardUnknown(m)
}

var xxx_messageInfo_ChainID proto.InternalMessageInfo

func (m *ChainID) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

type TokenAmount struct {
	TokenAmount          uint64   `protobuf:"varint,1,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenAmount) Reset()         { *m = TokenAmount{} }
func (m *TokenAmount) String() string { return proto.CompactTextString(m) }
func (*TokenAmount) ProtoMessage()    {}
func (*TokenAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *TokenAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAmount.Unmarshal(m, b)
}
func (m *TokenAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAmount.Marshal(b, m, deterministic)
}
func (m *TokenAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAmount.Merge(m, src)
}
func (m *TokenAmount) XXX_Size() int {
	return xxx_messageInfo_TokenAmount.Size(m)
}
func (m *TokenAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAmount.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAmount proto.InternalMessageInfo

func (m *TokenAmount) GetTokenAmount() uint64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

type LocksRoot struct {
	LocksRoot            []byte   `protobuf:"bytes,1,opt,name=locks_root,json=locksRoot,proto3" json:"locks_root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocksRoot) Reset()         { *m = LocksRoot{} }
func (m *LocksRoot) String() string { return proto.CompactTextString(m) }
func (*LocksRoot) ProtoMessage()    {}
func (*LocksRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *LocksRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocksRoot.Unmarshal(m, b)
}
func (m *LocksRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocksRoot.Marshal(b, m, deterministic)
}
func (m *LocksRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocksRoot.Merge(m, src)
}
func (m *LocksRoot) XXX_Size() int {
	return xxx_messageInfo_LocksRoot.Size(m)
}
func (m *LocksRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_LocksRoot.DiscardUnknown(m)
}

var xxx_messageInfo_LocksRoot proto.InternalMessageInfo

func (m *LocksRoot) GetLocksRoot() []byte {
	if m != nil {
		return m.LocksRoot
	}
	return nil
}

type ChannelID struct {
	ChannelId            uint64   `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelID) Reset()         { *m = ChannelID{} }
func (m *ChannelID) String() string { return proto.CompactTextString(m) }
func (*ChannelID) ProtoMessage()    {}
func (*ChannelID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ChannelID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelID.Unmarshal(m, b)
}
func (m *ChannelID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelID.Marshal(b, m, deterministic)
}
func (m *ChannelID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelID.Merge(m, src)
}
func (m *ChannelID) XXX_Size() int {
	return xxx_messageInfo_ChannelID.Size(m)
}
func (m *ChannelID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelID.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelID proto.InternalMessageInfo

func (m *ChannelID) GetChannelId() uint64 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

type TokenNetworkAddress struct {
	TokenNetworkAddress  []byte   `protobuf:"bytes,1,opt,name=token_network_address,json=tokenNetworkAddress,proto3" json:"token_network_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenNetworkAddress) Reset()         { *m = TokenNetworkAddress{} }
func (m *TokenNetworkAddress) String() string { return proto.CompactTextString(m) }
func (*TokenNetworkAddress) ProtoMessage()    {}
func (*TokenNetworkAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *TokenNetworkAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenNetworkAddress.Unmarshal(m, b)
}
func (m *TokenNetworkAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenNetworkAddress.Marshal(b, m, deterministic)
}
func (m *TokenNetworkAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenNetworkAddress.Merge(m, src)
}
func (m *TokenNetworkAddress) XXX_Size() int {
	return xxx_messageInfo_TokenNetworkAddress.Size(m)
}
func (m *TokenNetworkAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenNetworkAddress.DiscardUnknown(m)
}

var xxx_messageInfo_TokenNetworkAddress proto.InternalMessageInfo

func (m *TokenNetworkAddress) GetTokenNetworkAddress() []byte {
	if m != nil {
		return m.TokenNetworkAddress
	}
	return nil
}

type MessageID struct {
	MessageId            uint64   `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageID) Reset()         { *m = MessageID{} }
func (m *MessageID) String() string { return proto.CompactTextString(m) }
func (*MessageID) ProtoMessage()    {}
func (*MessageID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *MessageID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageID.Unmarshal(m, b)
}
func (m *MessageID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageID.Marshal(b, m, deterministic)
}
func (m *MessageID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageID.Merge(m, src)
}
func (m *MessageID) XXX_Size() int {
	return xxx_messageInfo_MessageID.Size(m)
}
func (m *MessageID) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageID.DiscardUnknown(m)
}

var xxx_messageInfo_MessageID proto.InternalMessageInfo

func (m *MessageID) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type PaymentID struct {
	PaymentId            uint64   `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentID) Reset()         { *m = PaymentID{} }
func (m *PaymentID) String() string { return proto.CompactTextString(m) }
func (*PaymentID) ProtoMessage()    {}
func (*PaymentID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *PaymentID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentID.Unmarshal(m, b)
}
func (m *PaymentID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentID.Marshal(b, m, deterministic)
}
func (m *PaymentID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentID.Merge(m, src)
}
func (m *PaymentID) XXX_Size() int {
	return xxx_messageInfo_PaymentID.Size(m)
}
func (m *PaymentID) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentID.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentID proto.InternalMessageInfo

func (m *PaymentID) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

type PaymentAmount struct {
	PaymentAmount        uint64   `protobuf:"varint,1,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentAmount) Reset()         { *m = PaymentAmount{} }
func (m *PaymentAmount) String() string { return proto.CompactTextString(m) }
func (*PaymentAmount) ProtoMessage()    {}
func (*PaymentAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *PaymentAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentAmount.Unmarshal(m, b)
}
func (m *PaymentAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentAmount.Marshal(b, m, deterministic)
}
func (m *PaymentAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentAmount.Merge(m, src)
}
func (m *PaymentAmount) XXX_Size() int {
	return xxx_messageInfo_PaymentAmount.Size(m)
}
func (m *PaymentAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentAmount.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentAmount proto.InternalMessageInfo

func (m *PaymentAmount) GetPaymentAmount() uint64 {
	if m != nil {
		return m.PaymentAmount
	}
	return 0
}

type SecretHash struct {
	SecretHash           []byte   `protobuf:"bytes,1,opt,name=secret_hash,json=secretHash,proto3" json:"secret_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretHash) Reset()         { *m = SecretHash{} }
func (m *SecretHash) String() string { return proto.CompactTextString(m) }
func (*SecretHash) ProtoMessage()    {}
func (*SecretHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *SecretHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretHash.Unmarshal(m, b)
}
func (m *SecretHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretHash.Marshal(b, m, deterministic)
}
func (m *SecretHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretHash.Merge(m, src)
}
func (m *SecretHash) XXX_Size() int {
	return xxx_messageInfo_SecretHash.Size(m)
}
func (m *SecretHash) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretHash.DiscardUnknown(m)
}

var xxx_messageInfo_SecretHash proto.InternalMessageInfo

func (m *SecretHash) GetSecretHash() []byte {
	if m != nil {
		return m.SecretHash
	}
	return nil
}

type BlockExpiration struct {
	BlockExpiration      uint64   `protobuf:"varint,1,opt,name=block_expiration,json=blockExpiration,proto3" json:"block_expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockExpiration) Reset()         { *m = BlockExpiration{} }
func (m *BlockExpiration) String() string { return proto.CompactTextString(m) }
func (*BlockExpiration) ProtoMessage()    {}
func (*BlockExpiration) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *BlockExpiration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockExpiration.Unmarshal(m, b)
}
func (m *BlockExpiration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockExpiration.Marshal(b, m, deterministic)
}
func (m *BlockExpiration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockExpiration.Merge(m, src)
}
func (m *BlockExpiration) XXX_Size() int {
	return xxx_messageInfo_BlockExpiration.Size(m)
}
func (m *BlockExpiration) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockExpiration.DiscardUnknown(m)
}

var xxx_messageInfo_BlockExpiration proto.InternalMessageInfo

func (m *BlockExpiration) GetBlockExpiration() uint64 {
	if m != nil {
		return m.BlockExpiration
	}
	return 0
}

type SecretType struct {
	Secret               []byte   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretType) Reset()         { *m = SecretType{} }
func (m *SecretType) String() string { return proto.CompactTextString(m) }
func (*SecretType) ProtoMessage()    {}
func (*SecretType) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *SecretType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretType.Unmarshal(m, b)
}
func (m *SecretType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretType.Marshal(b, m, deterministic)
}
func (m *SecretType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretType.Merge(m, src)
}
func (m *SecretType) XXX_Size() int {
	return xxx_messageInfo_SecretType.Size(m)
}
func (m *SecretType) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretType.DiscardUnknown(m)
}

var xxx_messageInfo_SecretType proto.InternalMessageInfo

func (m *SecretType) GetSecret() []byte {
	if m != nil {
		return m.Secret
	}
	return nil
}

type EncSecret struct {
	EncSecret            []byte   `protobuf:"bytes,1,opt,name=enc_secret,json=encSecret,proto3" json:"enc_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncSecret) Reset()         { *m = EncSecret{} }
func (m *EncSecret) String() string { return proto.CompactTextString(m) }
func (*EncSecret) ProtoMessage()    {}
func (*EncSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *EncSecret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncSecret.Unmarshal(m, b)
}
func (m *EncSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncSecret.Marshal(b, m, deterministic)
}
func (m *EncSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncSecret.Merge(m, src)
}
func (m *EncSecret) XXX_Size() int {
	return xxx_messageInfo_EncSecret.Size(m)
}
func (m *EncSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_EncSecret.DiscardUnknown(m)
}

var xxx_messageInfo_EncSecret proto.InternalMessageInfo

func (m *EncSecret) GetEncSecret() []byte {
	if m != nil {
		return m.EncSecret
	}
	return nil
}

type Address struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type HashTimeLock struct {
	Amount               *PaymentAmount   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Expiration           *BlockExpiration `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	SecretHash           *SecretHash      `protobuf:"bytes,3,opt,name=secret_hash,json=secretHash,proto3" json:"secret_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HashTimeLock) Reset()         { *m = HashTimeLock{} }
func (m *HashTimeLock) String() string { return proto.CompactTextString(m) }
func (*HashTimeLock) ProtoMessage()    {}
func (*HashTimeLock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *HashTimeLock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashTimeLock.Unmarshal(m, b)
}
func (m *HashTimeLock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashTimeLock.Marshal(b, m, deterministic)
}
func (m *HashTimeLock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashTimeLock.Merge(m, src)
}
func (m *HashTimeLock) XXX_Size() int {
	return xxx_messageInfo_HashTimeLock.Size(m)
}
func (m *HashTimeLock) XXX_DiscardUnknown() {
	xxx_messageInfo_HashTimeLock.DiscardUnknown(m)
}

var xxx_messageInfo_HashTimeLock proto.InternalMessageInfo

func (m *HashTimeLock) GetAmount() *PaymentAmount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *HashTimeLock) GetExpiration() *BlockExpiration {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *HashTimeLock) GetSecretHash() *SecretHash {
	if m != nil {
		return m.SecretHash
	}
	return nil
}

// messages definition
// SignedMessage(Message)
type SignedMessage struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Sender               *Address `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Publickey            []byte   `protobuf:"bytes,3,opt,name=publickey,proto3" json:"publickey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (m *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(m, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedMessage) GetSender() *Address {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *SignedMessage) GetPublickey() []byte {
	if m != nil {
		return m.Publickey
	}
	return nil
}

// EnvelopeMessage(SignedMessage)
//!!! check data to sign
type EnvelopeMessage struct {
	ChainId              *ChainID             `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce                uint64               `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TransferredAmount    *TokenAmount         `protobuf:"bytes,3,opt,name=transferred_amount,json=transferredAmount,proto3" json:"transferred_amount,omitempty"`
	LockedAmount         *TokenAmount         `protobuf:"bytes,4,opt,name=locked_amount,json=lockedAmount,proto3" json:"locked_amount,omitempty"`
	LocksRoot            *LocksRoot           `protobuf:"bytes,5,opt,name=locks_root,json=locksRoot,proto3" json:"locks_root,omitempty"`
	ChannelId            *ChannelID           `protobuf:"bytes,6,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	TokenNetworkAddress  *TokenNetworkAddress `protobuf:"bytes,7,opt,name=token_network_address,json=tokenNetworkAddress,proto3" json:"token_network_address,omitempty"`
	Signature            *SignedMessage       `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EnvelopeMessage) Reset()         { *m = EnvelopeMessage{} }
func (m *EnvelopeMessage) String() string { return proto.CompactTextString(m) }
func (*EnvelopeMessage) ProtoMessage()    {}
func (*EnvelopeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *EnvelopeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvelopeMessage.Unmarshal(m, b)
}
func (m *EnvelopeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvelopeMessage.Marshal(b, m, deterministic)
}
func (m *EnvelopeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvelopeMessage.Merge(m, src)
}
func (m *EnvelopeMessage) XXX_Size() int {
	return xxx_messageInfo_EnvelopeMessage.Size(m)
}
func (m *EnvelopeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvelopeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EnvelopeMessage proto.InternalMessageInfo

func (m *EnvelopeMessage) GetChainId() *ChainID {
	if m != nil {
		return m.ChainId
	}
	return nil
}

func (m *EnvelopeMessage) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *EnvelopeMessage) GetTransferredAmount() *TokenAmount {
	if m != nil {
		return m.TransferredAmount
	}
	return nil
}

func (m *EnvelopeMessage) GetLockedAmount() *TokenAmount {
	if m != nil {
		return m.LockedAmount
	}
	return nil
}

func (m *EnvelopeMessage) GetLocksRoot() *LocksRoot {
	if m != nil {
		return m.LocksRoot
	}
	return nil
}

func (m *EnvelopeMessage) GetChannelId() *ChannelID {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *EnvelopeMessage) GetTokenNetworkAddress() *TokenNetworkAddress {
	if m != nil {
		return m.TokenNetworkAddress
	}
	return nil
}

func (m *EnvelopeMessage) GetSignature() *SignedMessage {
	if m != nil {
		return m.Signature
	}
	return nil
}

//Processed(SignedMessage)
type Processed struct {
	MessageId            *MessageID     `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Signature            *SignedMessage `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Processed) Reset()         { *m = Processed{} }
func (m *Processed) String() string { return proto.CompactTextString(m) }
func (*Processed) ProtoMessage()    {}
func (*Processed) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *Processed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Processed.Unmarshal(m, b)
}
func (m *Processed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Processed.Marshal(b, m, deterministic)
}
func (m *Processed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Processed.Merge(m, src)
}
func (m *Processed) XXX_Size() int {
	return xxx_messageInfo_Processed.Size(m)
}
func (m *Processed) XXX_DiscardUnknown() {
	xxx_messageInfo_Processed.DiscardUnknown(m)
}

var xxx_messageInfo_Processed proto.InternalMessageInfo

func (m *Processed) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *Processed) GetSignature() *SignedMessage {
	if m != nil {
		return m.Signature
	}
	return nil
}

//Delivered(SignedMessage)
type Delivered struct {
	DeliveredMessageId   *MessageID     `protobuf:"bytes,1,opt,name=delivered_message_id,json=deliveredMessageId,proto3" json:"delivered_message_id,omitempty"`
	Signature            *SignedMessage `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Delivered) Reset()         { *m = Delivered{} }
func (m *Delivered) String() string { return proto.CompactTextString(m) }
func (*Delivered) ProtoMessage()    {}
func (*Delivered) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *Delivered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delivered.Unmarshal(m, b)
}
func (m *Delivered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delivered.Marshal(b, m, deterministic)
}
func (m *Delivered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delivered.Merge(m, src)
}
func (m *Delivered) XXX_Size() int {
	return xxx_messageInfo_Delivered.Size(m)
}
func (m *Delivered) XXX_DiscardUnknown() {
	xxx_messageInfo_Delivered.DiscardUnknown(m)
}

var xxx_messageInfo_Delivered proto.InternalMessageInfo

func (m *Delivered) GetDeliveredMessageId() *MessageID {
	if m != nil {
		return m.DeliveredMessageId
	}
	return nil
}

func (m *Delivered) GetSignature() *SignedMessage {
	if m != nil {
		return m.Signature
	}
	return nil
}

//SecretRequest(SignedMessage)
type SecretRequest struct {
	MessageId            *MessageID       `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PaymentId            *PaymentID       `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	SecretHash           *SecretHash      `protobuf:"bytes,3,opt,name=secret_hash,json=secretHash,proto3" json:"secret_hash,omitempty"`
	Amount               *TokenAmount     `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Expiration           *BlockExpiration `protobuf:"bytes,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Signature            *SignedMessage   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SecretRequest) Reset()         { *m = SecretRequest{} }
func (m *SecretRequest) String() string { return proto.CompactTextString(m) }
func (*SecretRequest) ProtoMessage()    {}
func (*SecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *SecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretRequest.Unmarshal(m, b)
}
func (m *SecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretRequest.Marshal(b, m, deterministic)
}
func (m *SecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretRequest.Merge(m, src)
}
func (m *SecretRequest) XXX_Size() int {
	return xxx_messageInfo_SecretRequest.Size(m)
}
func (m *SecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretRequest proto.InternalMessageInfo

func (m *SecretRequest) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *SecretRequest) GetPaymentId() *PaymentID {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *SecretRequest) GetSecretHash() *SecretHash {
	if m != nil {
		return m.SecretHash
	}
	return nil
}

func (m *SecretRequest) GetAmount() *TokenAmount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *SecretRequest) GetExpiration() *BlockExpiration {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *SecretRequest) GetSignature() *SignedMessage {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Secret(EnvelopeMessage)
type BalanceProof struct {
	EnvelopeMessage      *EnvelopeMessage `protobuf:"bytes,1,opt,name=envelope_message,json=envelopeMessage,proto3" json:"envelope_message,omitempty"`
	MessageId            *MessageID       `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PaymentId            *PaymentID       `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Secret               *SecretType      `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BalanceProof) Reset()         { *m = BalanceProof{} }
func (m *BalanceProof) String() string { return proto.CompactTextString(m) }
func (*BalanceProof) ProtoMessage()    {}
func (*BalanceProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *BalanceProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceProof.Unmarshal(m, b)
}
func (m *BalanceProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceProof.Marshal(b, m, deterministic)
}
func (m *BalanceProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceProof.Merge(m, src)
}
func (m *BalanceProof) XXX_Size() int {
	return xxx_messageInfo_BalanceProof.Size(m)
}
func (m *BalanceProof) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceProof.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceProof proto.InternalMessageInfo

func (m *BalanceProof) GetEnvelopeMessage() *EnvelopeMessage {
	if m != nil {
		return m.EnvelopeMessage
	}
	return nil
}

func (m *BalanceProof) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *BalanceProof) GetPaymentId() *PaymentID {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *BalanceProof) GetSecret() *SecretType {
	if m != nil {
		return m.Secret
	}
	return nil
}

// RevealSecret(SignedMessage)
type RevealSecret struct {
	MessageId            *MessageID     `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Secret               *SecretType    `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Signature            *SignedMessage `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RevealSecret) Reset()         { *m = RevealSecret{} }
func (m *RevealSecret) String() string { return proto.CompactTextString(m) }
func (*RevealSecret) ProtoMessage()    {}
func (*RevealSecret) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{20}
}

func (m *RevealSecret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevealSecret.Unmarshal(m, b)
}
func (m *RevealSecret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevealSecret.Marshal(b, m, deterministic)
}
func (m *RevealSecret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevealSecret.Merge(m, src)
}
func (m *RevealSecret) XXX_Size() int {
	return xxx_messageInfo_RevealSecret.Size(m)
}
func (m *RevealSecret) XXX_DiscardUnknown() {
	xxx_messageInfo_RevealSecret.DiscardUnknown(m)
}

var xxx_messageInfo_RevealSecret proto.InternalMessageInfo

func (m *RevealSecret) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *RevealSecret) GetSecret() *SecretType {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *RevealSecret) GetSignature() *SignedMessage {
	if m != nil {
		return m.Signature
	}
	return nil
}

// DirectTransfer(EnvelopeMessage)
type DirectTransfer struct {
	EnvelopeMessage      *EnvelopeMessage `protobuf:"bytes,1,opt,name=envelope_message,json=envelopeMessage,proto3" json:"envelope_message,omitempty"`
	MessageId            *MessageID       `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PaymentId            *PaymentID       `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Token                *Address         `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Recipient            *Address         `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DirectTransfer) Reset()         { *m = DirectTransfer{} }
func (m *DirectTransfer) String() string { return proto.CompactTextString(m) }
func (*DirectTransfer) ProtoMessage()    {}
func (*DirectTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{21}
}

func (m *DirectTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectTransfer.Unmarshal(m, b)
}
func (m *DirectTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectTransfer.Marshal(b, m, deterministic)
}
func (m *DirectTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectTransfer.Merge(m, src)
}
func (m *DirectTransfer) XXX_Size() int {
	return xxx_messageInfo_DirectTransfer.Size(m)
}
func (m *DirectTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_DirectTransfer proto.InternalMessageInfo

func (m *DirectTransfer) GetEnvelopeMessage() *EnvelopeMessage {
	if m != nil {
		return m.EnvelopeMessage
	}
	return nil
}

func (m *DirectTransfer) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *DirectTransfer) GetPaymentId() *PaymentID {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *DirectTransfer) GetToken() *Address {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *DirectTransfer) GetRecipient() *Address {
	if m != nil {
		return m.Recipient
	}
	return nil
}

// LockedTransferBase(EnvelopeMessage)
type LockedTransferBase struct {
	EnvelopeMessage      *EnvelopeMessage `protobuf:"bytes,1,opt,name=envelope_message,json=envelopeMessage,proto3" json:"envelope_message,omitempty"`
	MessageId            *MessageID       `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PaymentId            *PaymentID       `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Token                *Address         `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Recipient            *Address         `protobuf:"bytes,5,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Lock                 *HashTimeLock    `protobuf:"bytes,6,opt,name=lock,proto3" json:"lock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LockedTransferBase) Reset()         { *m = LockedTransferBase{} }
func (m *LockedTransferBase) String() string { return proto.CompactTextString(m) }
func (*LockedTransferBase) ProtoMessage()    {}
func (*LockedTransferBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{22}
}

func (m *LockedTransferBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockedTransferBase.Unmarshal(m, b)
}
func (m *LockedTransferBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockedTransferBase.Marshal(b, m, deterministic)
}
func (m *LockedTransferBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockedTransferBase.Merge(m, src)
}
func (m *LockedTransferBase) XXX_Size() int {
	return xxx_messageInfo_LockedTransferBase.Size(m)
}
func (m *LockedTransferBase) XXX_DiscardUnknown() {
	xxx_messageInfo_LockedTransferBase.DiscardUnknown(m)
}

var xxx_messageInfo_LockedTransferBase proto.InternalMessageInfo

func (m *LockedTransferBase) GetEnvelopeMessage() *EnvelopeMessage {
	if m != nil {
		return m.EnvelopeMessage
	}
	return nil
}

func (m *LockedTransferBase) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *LockedTransferBase) GetPaymentId() *PaymentID {
	if m != nil {
		return m.PaymentId
	}
	return nil
}

func (m *LockedTransferBase) GetToken() *Address {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *LockedTransferBase) GetRecipient() *Address {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *LockedTransferBase) GetLock() *HashTimeLock {
	if m != nil {
		return m.Lock
	}
	return nil
}

// LockedTransfer(LockedTransferBase)
type LockedTransfer struct {
	BaseMessage          *LockedTransferBase `protobuf:"bytes,1,opt,name=base_message,json=baseMessage,proto3" json:"base_message,omitempty"`
	Initiator            *Address            `protobuf:"bytes,2,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Target               *Address            `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	EncSecret            *EncSecret          `protobuf:"bytes,4,opt,name=enc_secret,json=encSecret,proto3" json:"enc_secret,omitempty"`
	Fee                  uint32              `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Mediators            []*Address          `protobuf:"bytes,6,rep,name=mediators,proto3" json:"mediators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LockedTransfer) Reset()         { *m = LockedTransfer{} }
func (m *LockedTransfer) String() string { return proto.CompactTextString(m) }
func (*LockedTransfer) ProtoMessage()    {}
func (*LockedTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{23}
}

func (m *LockedTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockedTransfer.Unmarshal(m, b)
}
func (m *LockedTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockedTransfer.Marshal(b, m, deterministic)
}
func (m *LockedTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockedTransfer.Merge(m, src)
}
func (m *LockedTransfer) XXX_Size() int {
	return xxx_messageInfo_LockedTransfer.Size(m)
}
func (m *LockedTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_LockedTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_LockedTransfer proto.InternalMessageInfo

func (m *LockedTransfer) GetBaseMessage() *LockedTransferBase {
	if m != nil {
		return m.BaseMessage
	}
	return nil
}

func (m *LockedTransfer) GetInitiator() *Address {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *LockedTransfer) GetTarget() *Address {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *LockedTransfer) GetEncSecret() *EncSecret {
	if m != nil {
		return m.EncSecret
	}
	return nil
}

func (m *LockedTransfer) GetFee() uint32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *LockedTransfer) GetMediators() []*Address {
	if m != nil {
		return m.Mediators
	}
	return nil
}

// RefundTransfer(LockedTransfer)
type RefundTransfer struct {
	Refund               *LockedTransfer `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RefundTransfer) Reset()         { *m = RefundTransfer{} }
func (m *RefundTransfer) String() string { return proto.CompactTextString(m) }
func (*RefundTransfer) ProtoMessage()    {}
func (*RefundTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{24}
}

func (m *RefundTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundTransfer.Unmarshal(m, b)
}
func (m *RefundTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundTransfer.Marshal(b, m, deterministic)
}
func (m *RefundTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundTransfer.Merge(m, src)
}
func (m *RefundTransfer) XXX_Size() int {
	return xxx_messageInfo_RefundTransfer.Size(m)
}
func (m *RefundTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_RefundTransfer proto.InternalMessageInfo

func (m *RefundTransfer) GetRefund() *LockedTransfer {
	if m != nil {
		return m.Refund
	}
	return nil
}

// LockExpired(EnvelopeMessage)
type LockExpired struct {
	EnvelopeMessage      *EnvelopeMessage `protobuf:"bytes,1,opt,name=envelope_message,json=envelopeMessage,proto3" json:"envelope_message,omitempty"`
	MessageId            *MessageID       `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Recipient            *Address         `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	SecretHash           *SecretHash      `protobuf:"bytes,4,opt,name=secret_hash,json=secretHash,proto3" json:"secret_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LockExpired) Reset()         { *m = LockExpired{} }
func (m *LockExpired) String() string { return proto.CompactTextString(m) }
func (*LockExpired) ProtoMessage()    {}
func (*LockExpired) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{25}
}

func (m *LockExpired) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockExpired.Unmarshal(m, b)
}
func (m *LockExpired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockExpired.Marshal(b, m, deterministic)
}
func (m *LockExpired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockExpired.Merge(m, src)
}
func (m *LockExpired) XXX_Size() int {
	return xxx_messageInfo_LockExpired.Size(m)
}
func (m *LockExpired) XXX_DiscardUnknown() {
	xxx_messageInfo_LockExpired.DiscardUnknown(m)
}

var xxx_messageInfo_LockExpired proto.InternalMessageInfo

func (m *LockExpired) GetEnvelopeMessage() *EnvelopeMessage {
	if m != nil {
		return m.EnvelopeMessage
	}
	return nil
}

func (m *LockExpired) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *LockExpired) GetRecipient() *Address {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *LockExpired) GetSecretHash() *SecretHash {
	if m != nil {
		return m.SecretHash
	}
	return nil
}

type WithdrawRequest struct {
	TokenNetworkAddress  *TokenNetworkAddress `protobuf:"bytes,1,opt,name=token_network_address,json=tokenNetworkAddress,proto3" json:"token_network_address,omitempty"`
	MessageId            *MessageID           `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId            *ChannelID           `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Participant          *Address             `protobuf:"bytes,4,opt,name=participant,proto3" json:"participant,omitempty"`
	WithdrawAmount       *TokenAmount         `protobuf:"bytes,5,opt,name=withdraw_amount,json=withdrawAmount,proto3" json:"withdraw_amount,omitempty"`
	ParticipantSignature *SignedMessage       `protobuf:"bytes,6,opt,name=participant_signature,json=participantSignature,proto3" json:"participant_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{26}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetTokenNetworkAddress() *TokenNetworkAddress {
	if m != nil {
		return m.TokenNetworkAddress
	}
	return nil
}

func (m *WithdrawRequest) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *WithdrawRequest) GetChannelId() *ChannelID {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *WithdrawRequest) GetParticipant() *Address {
	if m != nil {
		return m.Participant
	}
	return nil
}

func (m *WithdrawRequest) GetWithdrawAmount() *TokenAmount {
	if m != nil {
		return m.WithdrawAmount
	}
	return nil
}

func (m *WithdrawRequest) GetParticipantSignature() *SignedMessage {
	if m != nil {
		return m.ParticipantSignature
	}
	return nil
}

type Withdraw struct {
	TokenNetworkAddress  *TokenNetworkAddress `protobuf:"bytes,1,opt,name=token_network_address,json=tokenNetworkAddress,proto3" json:"token_network_address,omitempty"`
	MessageId            *MessageID           `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId            *ChannelID           `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Participant          *Address             `protobuf:"bytes,4,opt,name=participant,proto3" json:"participant,omitempty"`
	WithdrawAmount       *TokenAmount         `protobuf:"bytes,5,opt,name=withdraw_amount,json=withdrawAmount,proto3" json:"withdraw_amount,omitempty"`
	ParticipantSignature *SignedMessage       `protobuf:"bytes,6,opt,name=participant_signature,json=participantSignature,proto3" json:"participant_signature,omitempty"`
	PartnerSignature     *SignedMessage       `protobuf:"bytes,7,opt,name=partner_signature,json=partnerSignature,proto3" json:"partner_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Withdraw) Reset()         { *m = Withdraw{} }
func (m *Withdraw) String() string { return proto.CompactTextString(m) }
func (*Withdraw) ProtoMessage()    {}
func (*Withdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{27}
}

func (m *Withdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Withdraw.Unmarshal(m, b)
}
func (m *Withdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Withdraw.Marshal(b, m, deterministic)
}
func (m *Withdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdraw.Merge(m, src)
}
func (m *Withdraw) XXX_Size() int {
	return xxx_messageInfo_Withdraw.Size(m)
}
func (m *Withdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdraw.DiscardUnknown(m)
}

var xxx_messageInfo_Withdraw proto.InternalMessageInfo

func (m *Withdraw) GetTokenNetworkAddress() *TokenNetworkAddress {
	if m != nil {
		return m.TokenNetworkAddress
	}
	return nil
}

func (m *Withdraw) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *Withdraw) GetChannelId() *ChannelID {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *Withdraw) GetParticipant() *Address {
	if m != nil {
		return m.Participant
	}
	return nil
}

func (m *Withdraw) GetWithdrawAmount() *TokenAmount {
	if m != nil {
		return m.WithdrawAmount
	}
	return nil
}

func (m *Withdraw) GetParticipantSignature() *SignedMessage {
	if m != nil {
		return m.ParticipantSignature
	}
	return nil
}

func (m *Withdraw) GetPartnerSignature() *SignedMessage {
	if m != nil {
		return m.PartnerSignature
	}
	return nil
}

type CooperativeSettleRequest struct {
	TokenNetworkAddress   *TokenNetworkAddress `protobuf:"bytes,1,opt,name=token_network_address,json=tokenNetworkAddress,proto3" json:"token_network_address,omitempty"`
	MessageId             *MessageID           `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId             *ChannelID           `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Participant1          *Address             `protobuf:"bytes,4,opt,name=participant1,proto3" json:"participant1,omitempty"`
	Participant1Balance   *TokenAmount         `protobuf:"bytes,5,opt,name=participant1_balance,json=participant1Balance,proto3" json:"participant1_balance,omitempty"`
	Participant2          *Address             `protobuf:"bytes,6,opt,name=participant2,proto3" json:"participant2,omitempty"`
	Participant2Balance   *TokenAmount         `protobuf:"bytes,7,opt,name=participant2_balance,json=participant2Balance,proto3" json:"participant2_balance,omitempty"`
	Participant1Signature *SignedMessage       `protobuf:"bytes,8,opt,name=participant1_signature,json=participant1Signature,proto3" json:"participant1_signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *CooperativeSettleRequest) Reset()         { *m = CooperativeSettleRequest{} }
func (m *CooperativeSettleRequest) String() string { return proto.CompactTextString(m) }
func (*CooperativeSettleRequest) ProtoMessage()    {}
func (*CooperativeSettleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{28}
}

func (m *CooperativeSettleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CooperativeSettleRequest.Unmarshal(m, b)
}
func (m *CooperativeSettleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CooperativeSettleRequest.Marshal(b, m, deterministic)
}
func (m *CooperativeSettleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CooperativeSettleRequest.Merge(m, src)
}
func (m *CooperativeSettleRequest) XXX_Size() int {
	return xxx_messageInfo_CooperativeSettleRequest.Size(m)
}
func (m *CooperativeSettleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CooperativeSettleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CooperativeSettleRequest proto.InternalMessageInfo

func (m *CooperativeSettleRequest) GetTokenNetworkAddress() *TokenNetworkAddress {
	if m != nil {
		return m.TokenNetworkAddress
	}
	return nil
}

func (m *CooperativeSettleRequest) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *CooperativeSettleRequest) GetChannelId() *ChannelID {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *CooperativeSettleRequest) GetParticipant1() *Address {
	if m != nil {
		return m.Participant1
	}
	return nil
}

func (m *CooperativeSettleRequest) GetParticipant1Balance() *TokenAmount {
	if m != nil {
		return m.Participant1Balance
	}
	return nil
}

func (m *CooperativeSettleRequest) GetParticipant2() *Address {
	if m != nil {
		return m.Participant2
	}
	return nil
}

func (m *CooperativeSettleRequest) GetParticipant2Balance() *TokenAmount {
	if m != nil {
		return m.Participant2Balance
	}
	return nil
}

func (m *CooperativeSettleRequest) GetParticipant1Signature() *SignedMessage {
	if m != nil {
		return m.Participant1Signature
	}
	return nil
}

type CooperativeSettle struct {
	TokenNetworkAddress   *TokenNetworkAddress `protobuf:"bytes,1,opt,name=token_network_address,json=tokenNetworkAddress,proto3" json:"token_network_address,omitempty"`
	MessageId             *MessageID           `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId             *ChannelID           `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Participant1          *Address             `protobuf:"bytes,4,opt,name=participant1,proto3" json:"participant1,omitempty"`
	Participant1Balance   *TokenAmount         `protobuf:"bytes,5,opt,name=participant1_balance,json=participant1Balance,proto3" json:"participant1_balance,omitempty"`
	Participant2          *Address             `protobuf:"bytes,6,opt,name=participant2,proto3" json:"participant2,omitempty"`
	Participant2Balance   *TokenAmount         `protobuf:"bytes,7,opt,name=participant2_balance,json=participant2Balance,proto3" json:"participant2_balance,omitempty"`
	Participant1Signature *SignedMessage       `protobuf:"bytes,8,opt,name=participant1_signature,json=participant1Signature,proto3" json:"participant1_signature,omitempty"`
	Participant2Signature *SignedMessage       `protobuf:"bytes,9,opt,name=participant2_signature,json=participant2Signature,proto3" json:"participant2_signature,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *CooperativeSettle) Reset()         { *m = CooperativeSettle{} }
func (m *CooperativeSettle) String() string { return proto.CompactTextString(m) }
func (*CooperativeSettle) ProtoMessage()    {}
func (*CooperativeSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{29}
}

func (m *CooperativeSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CooperativeSettle.Unmarshal(m, b)
}
func (m *CooperativeSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CooperativeSettle.Marshal(b, m, deterministic)
}
func (m *CooperativeSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CooperativeSettle.Merge(m, src)
}
func (m *CooperativeSettle) XXX_Size() int {
	return xxx_messageInfo_CooperativeSettle.Size(m)
}
func (m *CooperativeSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_CooperativeSettle.DiscardUnknown(m)
}

var xxx_messageInfo_CooperativeSettle proto.InternalMessageInfo

func (m *CooperativeSettle) GetTokenNetworkAddress() *TokenNetworkAddress {
	if m != nil {
		return m.TokenNetworkAddress
	}
	return nil
}

func (m *CooperativeSettle) GetMessageId() *MessageID {
	if m != nil {
		return m.MessageId
	}
	return nil
}

func (m *CooperativeSettle) GetChannelId() *ChannelID {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *CooperativeSettle) GetParticipant1() *Address {
	if m != nil {
		return m.Participant1
	}
	return nil
}

func (m *CooperativeSettle) GetParticipant1Balance() *TokenAmount {
	if m != nil {
		return m.Participant1Balance
	}
	return nil
}

func (m *CooperativeSettle) GetParticipant2() *Address {
	if m != nil {
		return m.Participant2
	}
	return nil
}

func (m *CooperativeSettle) GetParticipant2Balance() *TokenAmount {
	if m != nil {
		return m.Participant2Balance
	}
	return nil
}

func (m *CooperativeSettle) GetParticipant1Signature() *SignedMessage {
	if m != nil {
		return m.Participant1Signature
	}
	return nil
}

func (m *CooperativeSettle) GetParticipant2Signature() *SignedMessage {
	if m != nil {
		return m.Participant2Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainID)(nil), "messages.ChainID")
	proto.RegisterType((*TokenAmount)(nil), "messages.TokenAmount")
	proto.RegisterType((*LocksRoot)(nil), "messages.LocksRoot")
	proto.RegisterType((*ChannelID)(nil), "messages.ChannelID")
	proto.RegisterType((*TokenNetworkAddress)(nil), "messages.TokenNetworkAddress")
	proto.RegisterType((*MessageID)(nil), "messages.MessageID")
	proto.RegisterType((*PaymentID)(nil), "messages.PaymentID")
	proto.RegisterType((*PaymentAmount)(nil), "messages.PaymentAmount")
	proto.RegisterType((*SecretHash)(nil), "messages.SecretHash")
	proto.RegisterType((*BlockExpiration)(nil), "messages.BlockExpiration")
	proto.RegisterType((*SecretType)(nil), "messages.SecretType")
	proto.RegisterType((*EncSecret)(nil), "messages.EncSecret")
	proto.RegisterType((*Address)(nil), "messages.Address")
	proto.RegisterType((*HashTimeLock)(nil), "messages.HashTimeLock")
	proto.RegisterType((*SignedMessage)(nil), "messages.SignedMessage")
	proto.RegisterType((*EnvelopeMessage)(nil), "messages.EnvelopeMessage")
	proto.RegisterType((*Processed)(nil), "messages.Processed")
	proto.RegisterType((*Delivered)(nil), "messages.Delivered")
	proto.RegisterType((*SecretRequest)(nil), "messages.SecretRequest")
	proto.RegisterType((*BalanceProof)(nil), "messages.BalanceProof")
	proto.RegisterType((*RevealSecret)(nil), "messages.RevealSecret")
	proto.RegisterType((*DirectTransfer)(nil), "messages.DirectTransfer")
	proto.RegisterType((*LockedTransferBase)(nil), "messages.LockedTransferBase")
	proto.RegisterType((*LockedTransfer)(nil), "messages.LockedTransfer")
	proto.RegisterType((*RefundTransfer)(nil), "messages.RefundTransfer")
	proto.RegisterType((*LockExpired)(nil), "messages.LockExpired")
	proto.RegisterType((*WithdrawRequest)(nil), "messages.WithdrawRequest")
	proto.RegisterType((*Withdraw)(nil), "messages.Withdraw")
	proto.RegisterType((*CooperativeSettleRequest)(nil), "messages.CooperativeSettleRequest")
	proto.RegisterType((*CooperativeSettle)(nil), "messages.CooperativeSettle")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 1218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x86, 0x2e, 0x96, 0xac, 0x23, 0xc9, 0xb2, 0xc7, 0x97, 0xdf, 0x01, 0x12, 0xfc, 0x29, 0x9b,
	0xa2, 0x4d, 0x90, 0xd8, 0xb1, 0x02, 0x17, 0x68, 0x51, 0xb4, 0x88, 0x2d, 0x03, 0x11, 0xe0, 0x04,
	0x0e, 0x6d, 0xa0, 0x4b, 0x81, 0x22, 0x8f, 0x2d, 0xc2, 0xf2, 0x90, 0x1d, 0x8e, 0xe5, 0xfa, 0x11,
	0xba, 0xea, 0xb6, 0x0f, 0x50, 0x20, 0xeb, 0xbe, 0x45, 0xbb, 0x69, 0xdf, 0xa3, 0x9b, 0xf6, 0x11,
	0x8a, 0x21, 0x67, 0xc8, 0x19, 0x46, 0x56, 0x58, 0x75, 0x11, 0xb4, 0xf0, 0xce, 0x33, 0xfc, 0xce,
	0x65, 0xbe, 0x73, 0xe6, 0x9b, 0x23, 0x43, 0xfb, 0x02, 0xa3, 0xc8, 0x39, 0xc3, 0xad, 0x90, 0x05,
	0x3c, 0x20, 0x8b, 0x72, 0x19, 0x59, 0x0f, 0xa0, 0xbe, 0x3f, 0x72, 0x7c, 0xda, 0xef, 0x91, 0x3b,
	0xb0, 0xe8, 0x8a, 0x3f, 0x07, 0xbe, 0xb7, 0x59, 0xba, 0x5f, 0xfa, 0xa4, 0x6a, 0xd7, 0xe3, 0x75,
	0xdf, 0xb3, 0x9e, 0x42, 0xf3, 0x24, 0x38, 0x47, 0xfa, 0xfc, 0x22, 0xb8, 0xa4, 0x9c, 0x7c, 0x00,
	0x2d, 0x2e, 0x96, 0x03, 0x27, 0x5e, 0x4b, 0x74, 0x93, 0x67, 0x10, 0xeb, 0x11, 0x34, 0x0e, 0x03,
	0xf7, 0x3c, 0xb2, 0x83, 0x80, 0x93, 0x7b, 0x00, 0x63, 0xb1, 0x18, 0xb0, 0x20, 0x48, 0xd0, 0x2d,
	0xbb, 0x31, 0x56, 0x9f, 0x05, 0x76, 0x7f, 0xe4, 0x50, 0x8a, 0xe3, 0x7e, 0x4f, 0x60, 0xdd, 0x64,
	0x91, 0xe5, 0xd1, 0x90, 0x3b, 0x7d, 0xcf, 0xea, 0xc3, 0x6a, 0x9c, 0xc9, 0x2b, 0xe4, 0x57, 0x01,
	0x3b, 0x7f, 0xee, 0x79, 0x0c, 0xa3, 0x88, 0x74, 0x61, 0x3d, 0xc9, 0x88, 0x26, 0xfb, 0x03, 0x27,
	0xf9, 0x20, 0x83, 0xad, 0xf2, 0xb7, 0x6d, 0x44, 0xd8, 0x97, 0x09, 0x0d, 0x49, 0x58, 0xc9, 0x89,
	0x16, 0x56, 0xee, 0xf4, 0x3d, 0x81, 0x3d, 0x72, 0xae, 0x2f, 0x90, 0xf2, 0x04, 0x1b, 0x26, 0x0b,
	0x0d, 0x2b, 0x77, 0xfa, 0x9e, 0xf5, 0x29, 0xb4, 0x25, 0x56, 0xd2, 0xf5, 0x11, 0x2c, 0x29, 0xbc,
	0x41, 0x58, 0x3b, 0xd4, 0x61, 0xd6, 0x13, 0x80, 0x63, 0x74, 0x19, 0xf2, 0x17, 0x4e, 0x34, 0x22,
	0xff, 0x87, 0x66, 0x14, 0xaf, 0x06, 0x23, 0x27, 0x1a, 0xc9, 0x73, 0x40, 0x94, 0x02, 0xac, 0x2f,
	0xa0, 0xb3, 0x27, 0x38, 0x3c, 0xf8, 0x36, 0xf4, 0x99, 0xc3, 0xfd, 0x80, 0x92, 0x87, 0xb0, 0x3c,
	0x14, 0x5b, 0x03, 0x4c, 0xf7, 0x64, 0xa8, 0xce, 0xd0, 0x84, 0x5a, 0x0f, 0x54, 0xb0, 0x93, 0xeb,
	0x10, 0xc9, 0x06, 0xd4, 0x12, 0xcf, 0x32, 0x8e, 0x5c, 0x89, 0x63, 0x1f, 0x50, 0x37, 0x01, 0x8a,
	0x63, 0x23, 0x75, 0x07, 0x06, 0xb0, 0x81, 0xea, 0xb3, 0xf5, 0x21, 0xd4, 0x55, 0x35, 0x36, 0xa1,
	0x6e, 0xf2, 0xaf, 0x96, 0xd6, 0x4f, 0x25, 0x68, 0x89, 0xec, 0x4f, 0xfc, 0x0b, 0x14, 0xfd, 0x41,
	0xb6, 0xa1, 0xa6, 0x71, 0xd2, 0xec, 0xfe, 0x6f, 0x4b, 0xb5, 0xe6, 0x96, 0x41, 0xa2, 0x2d, 0x61,
	0xe4, 0x33, 0x00, 0xed, 0x74, 0xe5, 0xd8, 0xe8, 0x4e, 0x66, 0x94, 0xa3, 0xc4, 0xd6, 0xc0, 0x64,
	0xd7, 0xa4, 0xb4, 0x12, 0xdb, 0xae, 0x65, 0xb6, 0x19, 0xfb, 0x06, 0xd1, 0x13, 0x68, 0x1f, 0xfb,
	0x67, 0x14, 0x3d, 0xd9, 0x2d, 0xe4, 0x2e, 0x34, 0x22, 0xff, 0x8c, 0x3a, 0xfc, 0x92, 0xa1, 0xe2,
	0x21, 0xdd, 0x20, 0x0f, 0x05, 0x97, 0xd4, 0x43, 0x26, 0x93, 0x5b, 0xc9, 0x02, 0x48, 0x7e, 0x6c,
	0x09, 0x10, 0x8e, 0xc2, 0xcb, 0xe1, 0xd8, 0x77, 0xcf, 0xf1, 0x3a, 0x4e, 0xa7, 0x65, 0x67, 0x1b,
	0xd6, 0x2f, 0x15, 0xe8, 0x1c, 0xd0, 0x09, 0x8e, 0x83, 0x10, 0x55, 0xe8, 0xc7, 0xb9, 0x3b, 0x6a,
	0xb8, 0x97, 0x17, 0x39, 0xbd, 0xb6, 0x64, 0x0d, 0x16, 0x68, 0x40, 0x5d, 0x8c, 0x33, 0xa9, 0xda,
	0xc9, 0x82, 0xf4, 0x80, 0x70, 0xe6, 0xd0, 0xe8, 0x14, 0x19, 0x43, 0x4f, 0xb5, 0x64, 0xc2, 0xc6,
	0x7a, 0xe6, 0x4d, 0xbb, 0xf0, 0xf6, 0x8a, 0x66, 0x20, 0x9b, 0xfa, 0x73, 0x68, 0x0b, 0xaa, 0x33,
	0x07, 0xd5, 0x59, 0x0e, 0x5a, 0x09, 0x56, 0xda, 0x76, 0x0d, 0x3d, 0x58, 0x88, 0x0d, 0x57, 0x33,
	0xc3, 0x54, 0x38, 0x34, 0x91, 0x10, 0x36, 0x9a, 0x2e, 0xd4, 0xf2, 0x36, 0xa9, 0x80, 0x68, 0x62,
	0x41, 0x5e, 0xdf, 0xa4, 0x0a, 0xf5, 0xd8, 0xfc, 0x5e, 0x2e, 0x57, 0x53, 0x1f, 0xa6, 0x8a, 0x06,
	0xd9, 0xd5, 0x6b, 0xbf, 0x98, 0x6f, 0x59, 0xa3, 0x4f, 0xb4, 0xa6, 0xb0, 0x26, 0xd0, 0x38, 0x62,
	0x81, 0x8b, 0x51, 0x84, 0x9e, 0x38, 0x4a, 0x4e, 0x6b, 0x8c, 0xa3, 0xa4, 0xa2, 0xa4, 0x09, 0x90,
	0x19, 0xb7, 0x5c, 0x38, 0xee, 0x77, 0x25, 0x68, 0xf4, 0x70, 0xec, 0x4f, 0x90, 0xa1, 0x47, 0x0e,
	0x60, 0xcd, 0x53, 0x8b, 0x41, 0xb1, 0x14, 0x48, 0x6a, 0xf0, 0xf2, 0x9f, 0xe6, 0xf2, 0x5b, 0x19,
	0xda, 0xc9, 0x15, 0xb3, 0xf1, 0x9b, 0x4b, 0x8c, 0xf8, 0x5c, 0x44, 0x74, 0x0d, 0xf1, 0x2d, 0xe7,
	0x6d, 0x52, 0x95, 0xd6, 0x14, 0x79, 0xce, 0x8b, 0x4f, 0x9e, 0xa4, 0xda, 0x34, 0xb3, 0xb7, 0xa7,
	0x2b, 0xd3, 0xc2, 0xdf, 0x53, 0x26, 0x8d, 0xd1, 0x5a, 0x61, 0x46, 0x7f, 0x2f, 0x41, 0x6b, 0xcf,
	0x19, 0x3b, 0xd4, 0xc5, 0x23, 0x16, 0x04, 0xa7, 0xa4, 0x07, 0xcb, 0x28, 0x15, 0x43, 0xd5, 0x57,
	0xd2, 0xaa, 0x25, 0x92, 0xd3, 0x14, 0xbb, 0x83, 0x39, 0x91, 0x31, 0xcb, 0x52, 0x9e, 0xa3, 0x2c,
	0x95, 0x42, 0x65, 0x79, 0x9c, 0xbe, 0x3a, 0xd5, 0xe9, 0x15, 0x11, 0x6f, 0x53, 0xfa, 0x16, 0xbd,
	0x29, 0x41, 0xcb, 0xc6, 0x09, 0x3a, 0x63, 0xf9, 0x1e, 0xcd, 0xd3, 0x3d, 0x59, 0xc8, 0xf2, 0xbb,
	0x43, 0xce, 0x5b, 0x96, 0x1f, 0xca, 0xb0, 0xd4, 0xf3, 0x19, 0xba, 0xfc, 0x44, 0xca, 0xe6, 0xbf,
	0xac, 0x30, 0x1f, 0xc3, 0x42, 0xac, 0x7d, 0xb2, 0x2e, 0x53, 0x5e, 0xb0, 0xe4, 0x3b, 0xd9, 0x86,
	0x06, 0x43, 0xd7, 0x0f, 0x7d, 0xa4, 0x4a, 0xc7, 0xa7, 0x80, 0x33, 0x8c, 0xf5, 0x73, 0x19, 0xc8,
	0x61, 0xfc, 0x14, 0x28, 0x6a, 0xf6, 0x9c, 0x08, 0x6f, 0xe9, 0x49, 0x30, 0xe4, 0x11, 0x54, 0x85,
	0x4a, 0xc8, 0x5e, 0xdb, 0xc8, 0xb0, 0xfa, 0xcc, 0x64, 0xc7, 0x18, 0xeb, 0xc7, 0x32, 0x2c, 0x99,
	0x54, 0x92, 0xaf, 0xa0, 0x35, 0x74, 0xa2, 0x3c, 0x85, 0x77, 0xcd, 0x97, 0xd5, 0xa4, 0xde, 0x6e,
	0x0a, 0x0b, 0xc5, 0xe0, 0x36, 0x34, 0x7c, 0xea, 0x73, 0xdf, 0xe1, 0xc1, 0x8c, 0xf1, 0x25, 0xc3,
	0x88, 0x61, 0x87, 0x3b, 0xec, 0x0c, 0xd5, 0xfc, 0x30, 0x6d, 0xd8, 0x49, 0x00, 0x82, 0x69, 0x6d,
	0x7c, 0xac, 0xe6, 0x99, 0x4e, 0xe7, 0x4c, 0x6d, 0xa6, 0x24, 0xcb, 0x50, 0x39, 0x45, 0x8c, 0xa9,
	0x6b, 0xdb, 0xe2, 0x4f, 0x91, 0xe1, 0x05, 0x7a, 0x71, 0xf0, 0x68, 0xb3, 0x76, 0xbf, 0x72, 0x43,
	0x86, 0x29, 0xc6, 0xda, 0x83, 0x25, 0x1b, 0x4f, 0x2f, 0x69, 0xc6, 0xd2, 0x53, 0xa8, 0xb1, 0x78,
	0x47, 0xf2, 0xb3, 0x79, 0x13, 0x3f, 0xb6, 0xc4, 0x59, 0x7f, 0x94, 0xa0, 0x79, 0xa8, 0xd4, 0x1b,
	0xbd, 0xf7, 0xd8, 0xae, 0x46, 0x47, 0x55, 0x0a, 0x74, 0x54, 0xee, 0xe9, 0xab, 0x16, 0x9c, 0x79,
	0xbf, 0xaf, 0x40, 0xe7, 0x6b, 0x9f, 0x8f, 0x3c, 0xe6, 0x5c, 0xa9, 0xd7, 0xfa, 0xf5, 0xac, 0xdf,
	0x58, 0xf3, 0x4d, 0x53, 0x73, 0xde, 0x58, 0x6d, 0x10, 0xac, 0x14, 0x1a, 0x04, 0x9f, 0x41, 0x33,
	0x74, 0x18, 0xf7, 0x5d, 0x3f, 0x74, 0xd2, 0xe7, 0x7c, 0x0a, 0x71, 0x3a, 0x8a, 0x7c, 0x09, 0x9d,
	0x2b, 0x49, 0x81, 0x9a, 0x71, 0x17, 0x66, 0xcd, 0x01, 0x4b, 0x0a, 0x2d, 0xa7, 0xdc, 0x43, 0x58,
	0xd7, 0xdc, 0x0d, 0x0a, 0xbf, 0x24, 0x6b, 0x9a, 0xd5, 0x71, 0xfa, 0xa8, 0xfc, 0x5a, 0x81, 0x45,
	0x55, 0x91, 0xdb, 0x52, 0xbc, 0xcf, 0x52, 0x90, 0x1e, 0xac, 0x88, 0x7d, 0x8a, 0x4c, 0xf3, 0x54,
	0x9f, 0xed, 0x69, 0x59, 0x5a, 0x64, 0x05, 0x7d, 0x53, 0x85, 0xcd, 0xfd, 0x20, 0x08, 0x51, 0xcc,
	0x80, 0x13, 0x3c, 0x46, 0xce, 0xc7, 0xf8, 0x1f, 0xb8, 0x6b, 0xbb, 0xd0, 0xd2, 0x58, 0xdb, 0xb9,
	0xb9, 0xc2, 0x06, 0x8c, 0xbc, 0x00, 0x9d, 0xec, 0x9d, 0xc1, 0x30, 0x99, 0x6b, 0x67, 0xd7, 0x79,
	0x55, 0x37, 0x91, 0x93, 0x70, 0x2e, 0x81, 0xae, 0xac, 0xf1, 0x3b, 0x12, 0xe8, 0xe6, 0x12, 0xe8,
	0xa6, 0x09, 0xd4, 0x8b, 0x26, 0xd0, 0x55, 0x09, 0xbc, 0x82, 0x0d, 0xe3, 0x28, 0x85, 0x7f, 0x30,
	0xea, 0x4d, 0xba, 0x93, 0x75, 0xca, 0x9f, 0x55, 0x58, 0x79, 0xab, 0x53, 0x6e, 0x5b, 0xe4, 0xb6,
	0x45, 0x32, 0x49, 0x32, 0xfd, 0x75, 0x35, 0x7f, 0x8d, 0xe2, 0xfe, 0xba, 0xa9, 0xbf, 0x61, 0x2d,
	0xfe, 0x3f, 0xf1, 0xb3, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x35, 0x0f, 0xfc, 0xaf, 0x38, 0x16,
	0x00, 0x00,
}
